//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesVI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesVI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Resources.ResourcesVI", typeof(ResourcesVI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để trợ giúp..
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ..
        /// </summary>
        public static string Error_ValidateData {
            get {
                return ResourceManager.GetString("Error_ValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được phép để trống..
        /// </summary>
        public static string Error_ValidateDepartmentCodeEmpty {
            get {
                return ResourceManager.GetString("Error_ValidateDepartmentCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id phòng ban không được để trống.
        /// </summary>
        public static string Error_ValidateDepartmentIdEmpty {
            get {
                return ResourceManager.GetString("Error_ValidateDepartmentIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được phép để trống..
        /// </summary>
        public static string Error_ValidateDepartmentNameEmpty {
            get {
                return ResourceManager.GetString("Error_ValidateDepartmentNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng..
        /// </summary>
        public static string Error_ValidateEmail {
            get {
                return ResourceManager.GetString("Error_ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống..
        /// </summary>
        public static string Error_ValidateEmployeeCodeEmpty {
            get {
                return ResourceManager.GetString("Error_ValidateEmployeeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được phép để trống..
        /// </summary>
        public static string Error_ValidateEmptyRequired {
            get {
                return ResourceManager.GetString("Error_ValidateEmptyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban đã tồn tại trong hệ thống..
        /// </summary>
        public static string Error_ValidateExistDepartmentCode {
            get {
                return ResourceManager.GetString("Error_ValidateExistDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống..
        /// </summary>
        public static string Error_ValidateExistEmployeeCode {
            get {
                return ResourceManager.GetString("Error_ValidateExistEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp dữ  liệu không tồn tại..
        /// </summary>
        public static string Error_ValidateFileNotExist {
            get {
                return ResourceManager.GetString("Error_ValidateFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên nhân viên không được phép để trống..
        /// </summary>
        public static string Error_ValidateFullNameEmpty {
            get {
                return ResourceManager.GetString("Error_ValidateFullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string Error_ValidateInputDateGreaterNow {
            get {
                return ResourceManager.GetString("Error_ValidateInputDateGreaterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được vượt quá 20 ký tự..
        /// </summary>
        public static string Error_ValidateLengthCode20 {
            get {
                return ResourceManager.GetString("Error_ValidateLengthCode20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp dữ liệu không đúng định dạng..
        /// </summary>
        public static string Error_ValidateMalformedDataFile {
            get {
                return ResourceManager.GetString("Error_ValidateMalformedDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vượt quá độ dài tối đa {1}..
        /// </summary>
        public static string Error_ValidateMaxLength {
            get {
                return ResourceManager.GetString("Error_ValidateMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không tồn tại trong hệ thống..
        /// </summary>
        public static string Error_ValidateNotExistDepartmentId {
            get {
                return ResourceManager.GetString("Error_ValidateNotExistDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại trong hệ thống..
        /// </summary>
        public static string Error_ValidateNotExistEmployeeId {
            get {
                return ResourceManager.GetString("Error_ValidateNotExistEmployeeId", resourceCulture);
            }
        }
    }
}
